"""Update employee and tax calculation models

Revision ID: 7fb6795f57c9
Revises: e3e43f401db3
Create Date: 2024-11-22 12:19:42.269782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7fb6795f57c9'
down_revision = 'e3e43f401db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create temporary table
    op.execute('''
        CREATE TABLE tax_calculation_new (
            id INTEGER NOT NULL PRIMARY KEY,
            employee_id INTEGER NOT NULL,
            gross_income FLOAT NOT NULL,
            deductions FLOAT NOT NULL,
            taxable_income FLOAT NOT NULL,
            tax_amount FLOAT NOT NULL,
            calculation_date DATETIME,
            FOREIGN KEY(employee_id) REFERENCES employee (id)
        )
    ''')
    
    # Drop the old table and rename the new one
    op.drop_table('tax_calculation')
    op.execute('ALTER TABLE tax_calculation_new RENAME TO tax_calculation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create temporary table
    op.execute('''
        CREATE TABLE tax_calculation_new (
            id INTEGER NOT NULL PRIMARY KEY,
            user_id INTEGER NOT NULL,
            income_data JSON NOT NULL,
            tax_result JSON NOT NULL,
            is_saved BOOLEAN,
            created_at DATETIME,
            FOREIGN KEY(user_id) REFERENCES employee (id)
        )
    ''')
    
    # Drop the new table and rename back to original
    op.drop_table('tax_calculation')
    op.execute('ALTER TABLE tax_calculation_new RENAME TO tax_calculation')
    # ### end Alembic commands ###
